#! /bin/sh

# start sxhkd if it is not running
pgrep -x sxhkd > /dev/null || sxhkd &

# See if hdmi monitor is connected
HDMICON=$(xrandr -q | grep 'HDMI-1-2.* connected' | cut -d' ' -f1)
export HDMICON
#          
if [ "$HDMICON" != "" ]; then
  bspc monitor eDP-1-1 -d     
  bspc monitor HDMI-1-2 -d     
  bspc rule -a Console desktop='^1' follow=on
  bspc rule -a Ranger desktop='^2' follow=on
  bspc rule -a Thunar desktop='^2' follow=on
  bspc rule -a Org.gnome.Nautilus desktop='^2' follow=on
  bspc rule -a qemu-system-x86_64 desktop='^3' state=fullscreen follow=on
  bspc rule -a Qemu-system-x86_64 desktop='^3' state=fullscreen follow=on
  # bspc rule -a Google-chrome desktop='^6' state=tiled follow=on
  bspc rule -a firefoxdeveloperedition desktop='^6' follow=on
  bspc rule -a Zathura desktop='^7' state=tiled follow=on
  bspc rule -a Wfica desktop='^8' state=tiled follow=on
else
  bspc monitor -d     
  bspc rule -a Console desktop='^1' follow=on
  # bspc rule -a Google-chrome desktop='^2' state=tiled follow=on
  bspc rule -a firefoxdeveloperedition desktop='^2' follow=on
  bspc rule -a Ranger desktop='^3' follow=on
  bspc rule -a Thunar desktop='^3' follow=on
  bspc rule -a Org.gnome.Nautilus desktop='^3' follow=on
  bspc rule -a Zathura desktop='^4' state=tiled follow=on
  bspc rule -a Wfica desktop='^5' state=tiled follow=on
  bspc rule -a qemu-system-x86_64 desktop='^5' state=fullscreen follow=on
  bspc rule -a Qemu-system-x86_64 desktop='^5' state=fullscreen follow=on
fi

bspc rule -a Emacs state=tiled follow=on

bspc config pointer_follows_focus   true
bspc config focus_follows_pointer   true
bspc config pointer_follows_monitor true
bspc config border_width         0
bspc config window_gap           4

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Border for non-active window
bspc config normal_border_color "#aaaaaa"
# Border for active window not on focused desktop
bspc config active_border_color "#00ffff"
# Border for active window on focused desktop
bspc config focused_border_color "#00ff00"

bspc rule -a Gimp state=floating follow=on
bspc rule -a Inkscape state=floating follow=on
bspc rule -a Shotwell state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a 'VirtualBox Manager' state=pseudo_tiled follow=on
# bspc rule -a Screenkey manage=off

# Fix mouse cursor
xsetroot -cursor_name left_ptr

# Start gnome settings daemon
# gnome-settings-daemon
# Start picom compositor
/usr/bin/picom --config "$HOME/.config/picom/picom.conf" -b
echo "picom started" > /home/ralph/bspwm.log
# Start dunst
/usr/bin/dunst -config "$HOME/.config/dunst/dunstrc" &
echo "dunst started" >> /home/ralph/bspwm.log
# Switch numlock on
/usr/bin/numlockx on
echo "numlock on" >> /home/ralph/bspwm.log
# Set volume
/usr/bin/pactl set-sink-volume 0 50%
echo "volume set" >> /home/ralph/bspwm.log
# Unlock keyring (done by dm already)
# /usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh
# echo "gnome-keyring-daemon started" >> /home/ralph/bspwm.log
# Start NetworkManager Applet
/usr/bin/nm-applet &
echo "nm-applet started" >> /home/ralph/bspwm.log
# Set wallpaper using feh
# /home/ralph/.fehbg > /home/ralph/fehbg.log
# echo "wallpaper set to:" >> /home/ralph/bspwm.log
# cat $HOME/.fehbg >> /home/ralph/bspwm.log
/usr/bin/nitrogen --restore &
# # Start dropbox
# /usr/bin/killall dropbox
# /usr/bin/systemctl --user start dropbox
# echo "dropbox started" >> /home/ralph/bspwm.log

# lxpolkit
/usr/bin/lxpolkit &

# Start polybar
/home/ralph/.config/polybar/launch.sh > /home/ralph/polybar.log
# echo "polybar started on main monitor" >> /home/ralph/bspwm.log
# if [ $HDMICON != '' ]; then
#   $HOME/.config/polybar/launch2.sh >> /home/ralph/polybar.log
#   echo "polybar started on HDMI-1-2" >> /home/ralph/bspwm.log
# fi
# # Start tint2
# killall tint2
# /usr/bin/tint2

# Start Plank
/usr/bin/plank &

# Turn off screen blanking
/usr/bin/xset -dpms s off

# Start kitty, Ranger and Firefox
/usr/bin/kitty --class Console --name Console &
# /usr/bin/kitty --class Ranger --name Ranger /usr/bin/ranger &
/usr/bin/nautilus --new-window &
/usr/bin/firefox-developer-edition &

# # Start Zathura (temporary)
# /usr/bin/zathura /home/ralph/Documents/Technical_Documents/BSD/AbsoluteFreeBSD_3e.pdf &

# # Swap capslock and escape
# /usr/bin/setxkbmap -layout 'us' -option caps:swapescape

# vim: ft=sh
