# Don't print a new line at the start of the prompt
add_newline = false
command_timeout = 2000

# Can replace the "❯" symbol in the prompt with "➜"
[character]
format = "$symbol "
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❮](bold green)"

[cmd_duration]
disabled = true

[directory]
truncation_length = 9
style = "bold cyan"
disabled = false

[jobs]
symbol = "+"
threshold = 1

# Package module. Currently supports npm, cargo, poetry, composer, gradle, julia and mix
[package]
symbol = "🎁"
disabled = false

