# Don't print a new line at the start of the prompt
add_newline = false

# Can replace the "❯" symbol in the prompt with "➜"
[character]
symbol = "❯"
vicmd_symbol = "❮"
error_symbol = "✗"
use_symbol_for_status = true
style_success = "green"
style_failure = "red"

[command_duration]
disabled = true

[directory]
truncation_length = 9
prefix = ""
style = "bold cyan"
disabled = false

[jobs]
symbol = "+"
threshold = 1

# Package module. Currently supports npm, cargo, poetry, composer, gradle, julia and mix
[package]
symbol = "🎁"
disabled = false

