#!/usr/bin/perl
#
# Copyright 2014 Pierre Mavro <deimos@deimos.fr>
# Copyright 2014 Vivien Didelot <vivien@didelot.org>
# Copyright 2014 Andreas Guldstrand <andreas.guldstrand@gmail.com>
# Licensed under the terms of the GNU GPL v3, or any later version.

use strict;
use warnings;
use utf8;
binmode *STDOUT, qw<:encoding(UTF-8)>;
use Getopt::Long;

# default values
my $t_low  = 15;
my $t_med  = 30;
my $t_high = 45;
my $t_warn = 60;
my $t_crit = 75;
my $t_max  = 90;
my $cpu_usage = -1;
my $instance = $ENV{BLOCK_INSTANCE} || 0;
my $glyph = " "; # Default to blank

sub help {
    print "Usage: cpu_usage [-w <warning>] [-c <critical>]\n";
    print "-w <percent>: warning threshold to become yellow\n";
    print "-c <percent>: critical threshold to become red\n";
    exit 0;
}

GetOptions("help|h" => \&help,
           "w=i"    => \$t_warn,
           "c=i"    => \$t_crit);

# Get CPU usage
$ENV{LC_ALL}="en_US"; # if mpstat is not run under en_US locale, things may break, so make sure it is
open (MPSTAT, "mpstat -P $instance |") or die;
while (<MPSTAT>) {
    if (/^.*\s+(\d+\.\d+)\s+$/) {
        $cpu_usage = 100 - $1; # 100% - %idle
        last;
    }
}
close(MPSTAT);

$cpu_usage eq -1 and die 'Can\'t find CPU information';

if ($cpu_usage < $t_low) {
    $glyph = "▁";
} elsif ($cpu_usage < $t_med) {
    $glyph = "▂";
} elsif ($cpu_usage < $t_high) {
    $glyph = "▄";
} elsif ($cpu_usage < $t_warn) {
    $glyph = "▅";
} elsif ($cpu_usage < $t_crit) {
    $glyph = "▆";
} elsif ($cpu_usage < $t_max) {
    $glyph = "▇";
} else {
    $glyph = "█"
}

# Print short_text, full_text
# printf "%.0f%%\n", $cpu_usage;
# printf "%.0f%%\n", $cpu_usage;
printf "%s\n", $glyph;
printf "%s\n", $cpu_usage;

# Print color, if needed
if ($cpu_usage < $t_low) {
    print "#00FF00\n";
} elsif ($cpu_usage < $t_med) {
    print "#A8FF00\n";
} elsif ($cpu_usage < $t_high) {
    print "#FFFF00\n";
} elsif ($cpu_usage < $t_warn) {
    print "#FFF600\n";
} elsif ($cpu_usage < $t_crit) {
    print "#FFAE00\n";
} else {
    print "#FF0000\n";
}

exit 0;
