#!/bin/sh
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

TYPE="${BLOCK_INSTANCE:-mem}"

awk -v type=$TYPE '
/^MemTotal:/ {
	mem_total=$2
}
/^MemFree:/ {
	mem_free=$2
}
/^Buffers:/ {
	mem_free+=$2
}
/^.*Cached:/ {
	mem_free+=$2
}
/^SwapTotal:/ {
	swap_total=$2
}
/^SwapFree:/ {
	swap_free=$2
}
END {
	# full text
	if (type == "swap")
		printf("%.1fG\n", (swap_total-swap_free)/1024/1024)
	else
		printf("%.1fG\n", (mem_total-mem_free)/1024/1024)

	# short text - same as full text
	if (type == "swap")
		printf("%.1fG\n", (swap_total-swap_free)/1024/1024)
	else
		printf("%.1fG\n", (mem_total-mem_free)/1024/1024)


	# color
        if (type == "swap")
                PCT=100*(swap_total-swap_free)/swap_total
        else
                PCT=100*(mem_total-mem_free)/mem_total

        if (PCT > 85)
            print("#FF0000")
        else
            if (PCT > 60)
                print("#FFAE00")
            else
                if (PCT > 40)
                    print("#FFF600")
                else
                    if (PCT > 20)
                        print("#A8FF00")
                    else
                        print("#00FF00")
}
' /proc/meminfo

