#!/usr/bin/env python3
# weather - Prints the weather for a location from the command line.

import json
import requests
from subprocess import call
import re
from datetime import datetime


def get_glyph(in_desc, in_hour):
    wglyph = '&#61829;'
    if re.match('.*clouds.*', in_desc):
        if (in_hour >= 6 and in_hour < 18):
            wglyph = '&#61620'
        else:
            wglyph = '&#61619;'
    else:
        if re.match('.*rain.*', in_desc):
            if (in_hour >= 6 and in_hour < 18):
                wglyph = '&#61620;'
            else:
                wglyph = '&#61619;'
        else:
            if re.match('.*storm.*', in_desc):
                wglyph = '&#61671;'
            else:
                if (in_hour >= 6 and in_hour < 18):
                    wglyph = '&#61829;'
                else:
                    wglyph = '&#61830;'
    return wglyph


location = 'Brisbane,AU'

# Download the JSON data from OpenWeatherMap.org's API
url = ('http://api.openweathermap.org/data/2.5/forecast/daily?q=%s&' +
       'APPID=b0d9aeb621f5e2763f5181c4ae051988') % location
response = requests.get(url)

if response is None:
    oWeather = '<span foreground="#808080">(?)??-??&#8451;</span>'
    wDescription = 'Weather Info Unavailable'
else:
    response.raise_for_status()
    fh = open('weather.json', 'w')
    fh.write(response.text)
    fh.close()
    # Load JSON data into a Python variable
    weatherData = json.loads(response.text)

    # Get weather descriptions
    w = weatherData['list']
    wToday = w[0]['weather'][0]['main'] + ' - ' + \
        w[0]['weather'][0]['description']

    # Get type of cloud cover
    wClouds = w[0]['clouds']
    wHour = int(datetime.now().strftime('%H'))

    minTemp = float(w[0]['temp']['min']) - 273.15
    maxTemp = float(w[0]['temp']['max']) - 273.15
    dayTemp = float(w[0]['temp']['day']) - 273.15

    if dayTemp < 18:
        wForeground = '\"#0000ff\"'
    else:
        if dayTemp <= 25:
            wForeground = '\"#ffff00\"'
        else:
            wForeground = '\"#ff0000\"'

    wMain = w[0]['weather'][0]['main']
    wDescription = w[0]['weather'][0]['description']

    wGlyph = get_glyph(wDescription, wHour)
    oWeather = '<span foreground=' + wForeground + '>' + wGlyph + ' ' + \
               format(minTemp, '0.0f') + '-' + format(maxTemp, '0.0f') + \
               ' &#8451;</span>'
#     oWeather = wGlyph + ' ' + \
#                format(minTemp, '0.0f') + '-' + format(maxTemp, '0.0f') + \
#                '&#8451;'

print(oWeather)
# call(['notify-send', wDescription])

