## {{{ Fonts
font_family Fira Code
bold_font   Fira Code Bold
italic_font Fira Mono Italic
bold_italic_font auto
font_size 16.0
disable_ligatures never
## }}}

## {{{ Cursor customization
cursor_shape underline
cursor_blink_interval 0
### }}}

## {{{ Scrollback
scrollback_lines 512
## }}}

## {{{ Mouse
mouse_hide_wait 3.0

url_style single
open_url_with default
url_prefixes http https file ftp

copy_on_select clipboard
strip_trailing_spaces smart
terminal_select_modifiers shift
## }}}

## {{{ Performance Tuning
# sync_to_monitor yes
## }}}

## {{{ Terminal bell
enable_audio_bell no
visual_bell_duration 0.0
window_alert_on_bell yes
bell_on_tab yes
command_on_bell none
## }}}

## {{{ Window Layout
enabled_layouts *
window_border_width 1.0
draw_minimal_borders yes
window_margin_width 0.0
window_padding_width 5.0
placement_strategy center
active_border_color #50fa7b
inactive_border_color #aaaaaa
bell_border_color #ff5a00
inactive_text_alpha 0.5
hide_window_decorations no
## }}}

## {{{ Color Scheme
# background_image ~/Wallpapers/Tiling/escheresque.png
# background_image_layout tiled
# background_opacity 1.0
# include dracula.conf
## }}}
## vim: foldmethod=marker
